/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoekenRouteImport } from './routes/zoeken'
import { Route as VoorzieningenRouteImport } from './routes/voorzieningen'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as VoertuigRouteImport } from './routes/voertuig'
import { Route as TruckstopsRouteImport } from './routes/truckstops'
import { Route as TerminalsRouteImport } from './routes/terminals'
import { Route as RouteplannerRouteImport } from './routes/routeplanner'
import { Route as RittenRouteImport } from './routes/ritten'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReleaseNotesRouteImport } from './routes/release-notes'
import { Route as ProfielRouteImport } from './routes/profiel'
import { Route as PrivacybeleidRouteImport } from './routes/privacybeleid'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OverRouteImport } from './routes/over'
import { Route as OntdekkenRouteImport } from './routes/ontdekken'
import { Route as OnderhoudRouteImport } from './routes/onderhoud'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfflineKaartenRouteImport } from './routes/offline-kaarten'
import { Route as NotificatiesRouteImport } from './routes/notificaties'
import { Route as NavigatieProviderRouteImport } from './routes/navigatie-provider'
import { Route as NavigatieRouteImport } from './routes/navigatie'
import { Route as MeldingenRouteImport } from './routes/meldingen'
import { Route as MeerRouteImport } from './routes/meer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KonvooiRouteImport } from './routes/konvooi'
import { Route as KaartRouteImport } from './routes/kaart'
import { Route as IntegratiesRouteImport } from './routes/integraties'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as GroepenRouteImport } from './routes/groepen'
import { Route as GeblokkeerdRouteImport } from './routes/geblokkeerd'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DocumentenRouteImport } from './routes/documenten'
import { Route as DeelEtaRouteImport } from './routes/deel-eta'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CarplayRouteImport } from './routes/carplay'
import { Route as BrandstofRouteImport } from './routes/brandstof'
import { Route as BeloningenRouteImport } from './routes/beloningen'
import { Route as BeheerRouteImport } from './routes/beheer'
import { Route as AssistentRouteImport } from './routes/assistent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TruckstopsIdRouteImport } from './routes/truckstops.$id'
import { Route as TerminalsIdRouteImport } from './routes/terminals.$id'
import { Route as RittenRideIdRouteImport } from './routes/ritten.$rideId'
import { Route as ProfielUserIdRouteImport } from './routes/profiel.$userId'
import { Route as KonvooiIdRouteImport } from './routes/konvooi.$id'
import { Route as GroepenIdRouteImport } from './routes/groepen.$id'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as BeheerMeldingenRouteImport } from './routes/beheer.meldingen'
import { Route as BeheerLocatiesRouteImport } from './routes/beheer.locaties'
import { Route as BeheerGebruikersRouteImport } from './routes/beheer.gebruikers'
import { Route as BeheerAuditlogRouteImport } from './routes/beheer.auditlog'
import { Route as ApiPublicHereKeyRouteImport } from './routes/api/public/here-key'

const ZoekenRoute = ZoekenRouteImport.update({
  id: '/zoeken',
  path: '/zoeken',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorzieningenRoute = VoorzieningenRouteImport.update({
  id: '/voorzieningen',
  path: '/voorzieningen',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorwaardenRoute = VoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const VoertuigRoute = VoertuigRouteImport.update({
  id: '/voertuig',
  path: '/voertuig',
  getParentRoute: () => rootRouteImport,
} as any)
const TruckstopsRoute = TruckstopsRouteImport.update({
  id: '/truckstops',
  path: '/truckstops',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalsRoute = TerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteplannerRoute = RouteplannerRouteImport.update({
  id: '/routeplanner',
  path: '/routeplanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RittenRoute = RittenRouteImport.update({
  id: '/ritten',
  path: '/ritten',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNotesRoute = ReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfielRoute = ProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacybeleidRoute = PrivacybeleidRouteImport.update({
  id: '/privacybeleid',
  path: '/privacybeleid',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OverRoute = OverRouteImport.update({
  id: '/over',
  path: '/over',
  getParentRoute: () => rootRouteImport,
} as any)
const OntdekkenRoute = OntdekkenRouteImport.update({
  id: '/ontdekken',
  path: '/ontdekken',
  getParentRoute: () => rootRouteImport,
} as any)
const OnderhoudRoute = OnderhoudRouteImport.update({
  id: '/onderhoud',
  path: '/onderhoud',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineKaartenRoute = OfflineKaartenRouteImport.update({
  id: '/offline-kaarten',
  path: '/offline-kaarten',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificatiesRoute = NotificatiesRouteImport.update({
  id: '/notificaties',
  path: '/notificaties',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatieProviderRoute = NavigatieProviderRouteImport.update({
  id: '/navigatie-provider',
  path: '/navigatie-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatieRoute = NavigatieRouteImport.update({
  id: '/navigatie',
  path: '/navigatie',
  getParentRoute: () => rootRouteImport,
} as any)
const MeldingenRoute = MeldingenRouteImport.update({
  id: '/meldingen',
  path: '/meldingen',
  getParentRoute: () => rootRouteImport,
} as any)
const MeerRoute = MeerRouteImport.update({
  id: '/meer',
  path: '/meer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KonvooiRoute = KonvooiRouteImport.update({
  id: '/konvooi',
  path: '/konvooi',
  getParentRoute: () => rootRouteImport,
} as any)
const KaartRoute = KaartRouteImport.update({
  id: '/kaart',
  path: '/kaart',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegratiesRoute = IntegratiesRouteImport.update({
  id: '/integraties',
  path: '/integraties',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const GroepenRoute = GroepenRouteImport.update({
  id: '/groepen',
  path: '/groepen',
  getParentRoute: () => rootRouteImport,
} as any)
const GeblokkeerdRoute = GeblokkeerdRouteImport.update({
  id: '/geblokkeerd',
  path: '/geblokkeerd',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentenRoute = DocumentenRouteImport.update({
  id: '/documenten',
  path: '/documenten',
  getParentRoute: () => rootRouteImport,
} as any)
const DeelEtaRoute = DeelEtaRouteImport.update({
  id: '/deel-eta',
  path: '/deel-eta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CarplayRoute = CarplayRouteImport.update({
  id: '/carplay',
  path: '/carplay',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandstofRoute = BrandstofRouteImport.update({
  id: '/brandstof',
  path: '/brandstof',
  getParentRoute: () => rootRouteImport,
} as any)
const BeloningenRoute = BeloningenRouteImport.update({
  id: '/beloningen',
  path: '/beloningen',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerRoute = BeheerRouteImport.update({
  id: '/beheer',
  path: '/beheer',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistentRoute = AssistentRouteImport.update({
  id: '/assistent',
  path: '/assistent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruckstopsIdRoute = TruckstopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TruckstopsRoute,
} as any)
const TerminalsIdRoute = TerminalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TerminalsRoute,
} as any)
const RittenRideIdRoute = RittenRideIdRouteImport.update({
  id: '/$rideId',
  path: '/$rideId',
  getParentRoute: () => RittenRoute,
} as any)
const ProfielUserIdRoute = ProfielUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfielRoute,
} as any)
const KonvooiIdRoute = KonvooiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KonvooiRoute,
} as any)
const GroepenIdRoute = GroepenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GroepenRoute,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatRoute,
} as any)
const BeheerMeldingenRoute = BeheerMeldingenRouteImport.update({
  id: '/meldingen',
  path: '/meldingen',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerLocatiesRoute = BeheerLocatiesRouteImport.update({
  id: '/locaties',
  path: '/locaties',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerGebruikersRoute = BeheerGebruikersRouteImport.update({
  id: '/gebruikers',
  path: '/gebruikers',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerAuditlogRoute = BeheerAuditlogRouteImport.update({
  id: '/auditlog',
  path: '/auditlog',
  getParentRoute: () => BeheerRoute,
} as any)
const ApiPublicHereKeyRoute = ApiPublicHereKeyRouteImport.update({
  id: '/api/public/here-key',
  path: '/api/public/here-key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistent': typeof AssistentRoute
  '/beheer': typeof BeheerRouteWithChildren
  '/beloningen': typeof BeloningenRoute
  '/brandstof': typeof BrandstofRoute
  '/carplay': typeof CarplayRoute
  '/chat': typeof ChatRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/deel-eta': typeof DeelEtaRoute
  '/documenten': typeof DocumentenRoute
  '/fleet': typeof FleetRoute
  '/geblokkeerd': typeof GeblokkeerdRoute
  '/groepen': typeof GroepenRouteWithChildren
  '/instellingen': typeof InstellingenRoute
  '/integraties': typeof IntegratiesRoute
  '/kaart': typeof KaartRoute
  '/konvooi': typeof KonvooiRouteWithChildren
  '/login': typeof LoginRoute
  '/meer': typeof MeerRoute
  '/meldingen': typeof MeldingenRoute
  '/navigatie': typeof NavigatieRoute
  '/navigatie-provider': typeof NavigatieProviderRoute
  '/notificaties': typeof NotificatiesRoute
  '/offline-kaarten': typeof OfflineKaartenRoute
  '/onboarding': typeof OnboardingRoute
  '/onderhoud': typeof OnderhoudRoute
  '/ontdekken': typeof OntdekkenRoute
  '/over': typeof OverRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/profiel': typeof ProfielRouteWithChildren
  '/release-notes': typeof ReleaseNotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ritten': typeof RittenRouteWithChildren
  '/routeplanner': typeof RouteplannerRoute
  '/terminals': typeof TerminalsRouteWithChildren
  '/truckstops': typeof TruckstopsRouteWithChildren
  '/voertuig': typeof VoertuigRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/voorzieningen': typeof VoorzieningenRoute
  '/zoeken': typeof ZoekenRoute
  '/beheer/auditlog': typeof BeheerAuditlogRoute
  '/beheer/gebruikers': typeof BeheerGebruikersRoute
  '/beheer/locaties': typeof BeheerLocatiesRoute
  '/beheer/meldingen': typeof BeheerMeldingenRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/groepen/$id': typeof GroepenIdRoute
  '/konvooi/$id': typeof KonvooiIdRoute
  '/profiel/$userId': typeof ProfielUserIdRoute
  '/ritten/$rideId': typeof RittenRideIdRoute
  '/terminals/$id': typeof TerminalsIdRoute
  '/truckstops/$id': typeof TruckstopsIdRoute
  '/api/public/here-key': typeof ApiPublicHereKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistent': typeof AssistentRoute
  '/beheer': typeof BeheerRouteWithChildren
  '/beloningen': typeof BeloningenRoute
  '/brandstof': typeof BrandstofRoute
  '/carplay': typeof CarplayRoute
  '/chat': typeof ChatRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/deel-eta': typeof DeelEtaRoute
  '/documenten': typeof DocumentenRoute
  '/fleet': typeof FleetRoute
  '/geblokkeerd': typeof GeblokkeerdRoute
  '/groepen': typeof GroepenRouteWithChildren
  '/instellingen': typeof InstellingenRoute
  '/integraties': typeof IntegratiesRoute
  '/kaart': typeof KaartRoute
  '/konvooi': typeof KonvooiRouteWithChildren
  '/login': typeof LoginRoute
  '/meer': typeof MeerRoute
  '/meldingen': typeof MeldingenRoute
  '/navigatie': typeof NavigatieRoute
  '/navigatie-provider': typeof NavigatieProviderRoute
  '/notificaties': typeof NotificatiesRoute
  '/offline-kaarten': typeof OfflineKaartenRoute
  '/onboarding': typeof OnboardingRoute
  '/onderhoud': typeof OnderhoudRoute
  '/ontdekken': typeof OntdekkenRoute
  '/over': typeof OverRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/profiel': typeof ProfielRouteWithChildren
  '/release-notes': typeof ReleaseNotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ritten': typeof RittenRouteWithChildren
  '/routeplanner': typeof RouteplannerRoute
  '/terminals': typeof TerminalsRouteWithChildren
  '/truckstops': typeof TruckstopsRouteWithChildren
  '/voertuig': typeof VoertuigRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/voorzieningen': typeof VoorzieningenRoute
  '/zoeken': typeof ZoekenRoute
  '/beheer/auditlog': typeof BeheerAuditlogRoute
  '/beheer/gebruikers': typeof BeheerGebruikersRoute
  '/beheer/locaties': typeof BeheerLocatiesRoute
  '/beheer/meldingen': typeof BeheerMeldingenRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/groepen/$id': typeof GroepenIdRoute
  '/konvooi/$id': typeof KonvooiIdRoute
  '/profiel/$userId': typeof ProfielUserIdRoute
  '/ritten/$rideId': typeof RittenRideIdRoute
  '/terminals/$id': typeof TerminalsIdRoute
  '/truckstops/$id': typeof TruckstopsIdRoute
  '/api/public/here-key': typeof ApiPublicHereKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistent': typeof AssistentRoute
  '/beheer': typeof BeheerRouteWithChildren
  '/beloningen': typeof BeloningenRoute
  '/brandstof': typeof BrandstofRoute
  '/carplay': typeof CarplayRoute
  '/chat': typeof ChatRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/deel-eta': typeof DeelEtaRoute
  '/documenten': typeof DocumentenRoute
  '/fleet': typeof FleetRoute
  '/geblokkeerd': typeof GeblokkeerdRoute
  '/groepen': typeof GroepenRouteWithChildren
  '/instellingen': typeof InstellingenRoute
  '/integraties': typeof IntegratiesRoute
  '/kaart': typeof KaartRoute
  '/konvooi': typeof KonvooiRouteWithChildren
  '/login': typeof LoginRoute
  '/meer': typeof MeerRoute
  '/meldingen': typeof MeldingenRoute
  '/navigatie': typeof NavigatieRoute
  '/navigatie-provider': typeof NavigatieProviderRoute
  '/notificaties': typeof NotificatiesRoute
  '/offline-kaarten': typeof OfflineKaartenRoute
  '/onboarding': typeof OnboardingRoute
  '/onderhoud': typeof OnderhoudRoute
  '/ontdekken': typeof OntdekkenRoute
  '/over': typeof OverRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/profiel': typeof ProfielRouteWithChildren
  '/release-notes': typeof ReleaseNotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ritten': typeof RittenRouteWithChildren
  '/routeplanner': typeof RouteplannerRoute
  '/terminals': typeof TerminalsRouteWithChildren
  '/truckstops': typeof TruckstopsRouteWithChildren
  '/voertuig': typeof VoertuigRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/voorzieningen': typeof VoorzieningenRoute
  '/zoeken': typeof ZoekenRoute
  '/beheer/auditlog': typeof BeheerAuditlogRoute
  '/beheer/gebruikers': typeof BeheerGebruikersRoute
  '/beheer/locaties': typeof BeheerLocatiesRoute
  '/beheer/meldingen': typeof BeheerMeldingenRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/groepen/$id': typeof GroepenIdRoute
  '/konvooi/$id': typeof KonvooiIdRoute
  '/profiel/$userId': typeof ProfielUserIdRoute
  '/ritten/$rideId': typeof RittenRideIdRoute
  '/terminals/$id': typeof TerminalsIdRoute
  '/truckstops/$id': typeof TruckstopsIdRoute
  '/api/public/here-key': typeof ApiPublicHereKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistent'
    | '/beheer'
    | '/beloningen'
    | '/brandstof'
    | '/carplay'
    | '/chat'
    | '/community'
    | '/contact'
    | '/deel-eta'
    | '/documenten'
    | '/fleet'
    | '/geblokkeerd'
    | '/groepen'
    | '/instellingen'
    | '/integraties'
    | '/kaart'
    | '/konvooi'
    | '/login'
    | '/meer'
    | '/meldingen'
    | '/navigatie'
    | '/navigatie-provider'
    | '/notificaties'
    | '/offline-kaarten'
    | '/onboarding'
    | '/onderhoud'
    | '/ontdekken'
    | '/over'
    | '/premium'
    | '/privacy'
    | '/privacybeleid'
    | '/profiel'
    | '/release-notes'
    | '/reset-password'
    | '/ritten'
    | '/routeplanner'
    | '/terminals'
    | '/truckstops'
    | '/voertuig'
    | '/voorwaarden'
    | '/voorzieningen'
    | '/zoeken'
    | '/beheer/auditlog'
    | '/beheer/gebruikers'
    | '/beheer/locaties'
    | '/beheer/meldingen'
    | '/chat/$chatId'
    | '/groepen/$id'
    | '/konvooi/$id'
    | '/profiel/$userId'
    | '/ritten/$rideId'
    | '/terminals/$id'
    | '/truckstops/$id'
    | '/api/public/here-key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistent'
    | '/beheer'
    | '/beloningen'
    | '/brandstof'
    | '/carplay'
    | '/chat'
    | '/community'
    | '/contact'
    | '/deel-eta'
    | '/documenten'
    | '/fleet'
    | '/geblokkeerd'
    | '/groepen'
    | '/instellingen'
    | '/integraties'
    | '/kaart'
    | '/konvooi'
    | '/login'
    | '/meer'
    | '/meldingen'
    | '/navigatie'
    | '/navigatie-provider'
    | '/notificaties'
    | '/offline-kaarten'
    | '/onboarding'
    | '/onderhoud'
    | '/ontdekken'
    | '/over'
    | '/premium'
    | '/privacy'
    | '/privacybeleid'
    | '/profiel'
    | '/release-notes'
    | '/reset-password'
    | '/ritten'
    | '/routeplanner'
    | '/terminals'
    | '/truckstops'
    | '/voertuig'
    | '/voorwaarden'
    | '/voorzieningen'
    | '/zoeken'
    | '/beheer/auditlog'
    | '/beheer/gebruikers'
    | '/beheer/locaties'
    | '/beheer/meldingen'
    | '/chat/$chatId'
    | '/groepen/$id'
    | '/konvooi/$id'
    | '/profiel/$userId'
    | '/ritten/$rideId'
    | '/terminals/$id'
    | '/truckstops/$id'
    | '/api/public/here-key'
  id:
    | '__root__'
    | '/'
    | '/assistent'
    | '/beheer'
    | '/beloningen'
    | '/brandstof'
    | '/carplay'
    | '/chat'
    | '/community'
    | '/contact'
    | '/deel-eta'
    | '/documenten'
    | '/fleet'
    | '/geblokkeerd'
    | '/groepen'
    | '/instellingen'
    | '/integraties'
    | '/kaart'
    | '/konvooi'
    | '/login'
    | '/meer'
    | '/meldingen'
    | '/navigatie'
    | '/navigatie-provider'
    | '/notificaties'
    | '/offline-kaarten'
    | '/onboarding'
    | '/onderhoud'
    | '/ontdekken'
    | '/over'
    | '/premium'
    | '/privacy'
    | '/privacybeleid'
    | '/profiel'
    | '/release-notes'
    | '/reset-password'
    | '/ritten'
    | '/routeplanner'
    | '/terminals'
    | '/truckstops'
    | '/voertuig'
    | '/voorwaarden'
    | '/voorzieningen'
    | '/zoeken'
    | '/beheer/auditlog'
    | '/beheer/gebruikers'
    | '/beheer/locaties'
    | '/beheer/meldingen'
    | '/chat/$chatId'
    | '/groepen/$id'
    | '/konvooi/$id'
    | '/profiel/$userId'
    | '/ritten/$rideId'
    | '/terminals/$id'
    | '/truckstops/$id'
    | '/api/public/here-key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistentRoute: typeof AssistentRoute
  BeheerRoute: typeof BeheerRouteWithChildren
  BeloningenRoute: typeof BeloningenRoute
  BrandstofRoute: typeof BrandstofRoute
  CarplayRoute: typeof CarplayRoute
  ChatRoute: typeof ChatRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DeelEtaRoute: typeof DeelEtaRoute
  DocumentenRoute: typeof DocumentenRoute
  FleetRoute: typeof FleetRoute
  GeblokkeerdRoute: typeof GeblokkeerdRoute
  GroepenRoute: typeof GroepenRouteWithChildren
  InstellingenRoute: typeof InstellingenRoute
  IntegratiesRoute: typeof IntegratiesRoute
  KaartRoute: typeof KaartRoute
  KonvooiRoute: typeof KonvooiRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeerRoute: typeof MeerRoute
  MeldingenRoute: typeof MeldingenRoute
  NavigatieRoute: typeof NavigatieRoute
  NavigatieProviderRoute: typeof NavigatieProviderRoute
  NotificatiesRoute: typeof NotificatiesRoute
  OfflineKaartenRoute: typeof OfflineKaartenRoute
  OnboardingRoute: typeof OnboardingRoute
  OnderhoudRoute: typeof OnderhoudRoute
  OntdekkenRoute: typeof OntdekkenRoute
  OverRoute: typeof OverRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacybeleidRoute: typeof PrivacybeleidRoute
  ProfielRoute: typeof ProfielRouteWithChildren
  ReleaseNotesRoute: typeof ReleaseNotesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RittenRoute: typeof RittenRouteWithChildren
  RouteplannerRoute: typeof RouteplannerRoute
  TerminalsRoute: typeof TerminalsRouteWithChildren
  TruckstopsRoute: typeof TruckstopsRouteWithChildren
  VoertuigRoute: typeof VoertuigRoute
  VoorwaardenRoute: typeof VoorwaardenRoute
  VoorzieningenRoute: typeof VoorzieningenRoute
  ZoekenRoute: typeof ZoekenRoute
  ApiPublicHereKeyRoute: typeof ApiPublicHereKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zoeken': {
      id: '/zoeken'
      path: '/zoeken'
      fullPath: '/zoeken'
      preLoaderRoute: typeof ZoekenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voorzieningen': {
      id: '/voorzieningen'
      path: '/voorzieningen'
      fullPath: '/voorzieningen'
      preLoaderRoute: typeof VoorzieningenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voorwaarden': {
      id: '/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof VoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voertuig': {
      id: '/voertuig'
      path: '/voertuig'
      fullPath: '/voertuig'
      preLoaderRoute: typeof VoertuigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truckstops': {
      id: '/truckstops'
      path: '/truckstops'
      fullPath: '/truckstops'
      preLoaderRoute: typeof TruckstopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminals': {
      id: '/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof TerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routeplanner': {
      id: '/routeplanner'
      path: '/routeplanner'
      fullPath: '/routeplanner'
      preLoaderRoute: typeof RouteplannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritten': {
      id: '/ritten'
      path: '/ritten'
      fullPath: '/ritten'
      preLoaderRoute: typeof RittenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-notes': {
      id: '/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof ReleaseNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiel': {
      id: '/profiel'
      path: '/profiel'
      fullPath: '/profiel'
      preLoaderRoute: typeof ProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacybeleid': {
      id: '/privacybeleid'
      path: '/privacybeleid'
      fullPath: '/privacybeleid'
      preLoaderRoute: typeof PrivacybeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over': {
      id: '/over'
      path: '/over'
      fullPath: '/over'
      preLoaderRoute: typeof OverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ontdekken': {
      id: '/ontdekken'
      path: '/ontdekken'
      fullPath: '/ontdekken'
      preLoaderRoute: typeof OntdekkenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onderhoud': {
      id: '/onderhoud'
      path: '/onderhoud'
      fullPath: '/onderhoud'
      preLoaderRoute: typeof OnderhoudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline-kaarten': {
      id: '/offline-kaarten'
      path: '/offline-kaarten'
      fullPath: '/offline-kaarten'
      preLoaderRoute: typeof OfflineKaartenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaties': {
      id: '/notificaties'
      path: '/notificaties'
      fullPath: '/notificaties'
      preLoaderRoute: typeof NotificatiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigatie-provider': {
      id: '/navigatie-provider'
      path: '/navigatie-provider'
      fullPath: '/navigatie-provider'
      preLoaderRoute: typeof NavigatieProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigatie': {
      id: '/navigatie'
      path: '/navigatie'
      fullPath: '/navigatie'
      preLoaderRoute: typeof NavigatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meldingen': {
      id: '/meldingen'
      path: '/meldingen'
      fullPath: '/meldingen'
      preLoaderRoute: typeof MeldingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meer': {
      id: '/meer'
      path: '/meer'
      fullPath: '/meer'
      preLoaderRoute: typeof MeerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konvooi': {
      id: '/konvooi'
      path: '/konvooi'
      fullPath: '/konvooi'
      preLoaderRoute: typeof KonvooiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaart': {
      id: '/kaart'
      path: '/kaart'
      fullPath: '/kaart'
      preLoaderRoute: typeof KaartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integraties': {
      id: '/integraties'
      path: '/integraties'
      fullPath: '/integraties'
      preLoaderRoute: typeof IntegratiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groepen': {
      id: '/groepen'
      path: '/groepen'
      fullPath: '/groepen'
      preLoaderRoute: typeof GroepenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geblokkeerd': {
      id: '/geblokkeerd'
      path: '/geblokkeerd'
      fullPath: '/geblokkeerd'
      preLoaderRoute: typeof GeblokkeerdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documenten': {
      id: '/documenten'
      path: '/documenten'
      fullPath: '/documenten'
      preLoaderRoute: typeof DocumentenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deel-eta': {
      id: '/deel-eta'
      path: '/deel-eta'
      fullPath: '/deel-eta'
      preLoaderRoute: typeof DeelEtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carplay': {
      id: '/carplay'
      path: '/carplay'
      fullPath: '/carplay'
      preLoaderRoute: typeof CarplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brandstof': {
      id: '/brandstof'
      path: '/brandstof'
      fullPath: '/brandstof'
      preLoaderRoute: typeof BrandstofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beloningen': {
      id: '/beloningen'
      path: '/beloningen'
      fullPath: '/beloningen'
      preLoaderRoute: typeof BeloningenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer': {
      id: '/beheer'
      path: '/beheer'
      fullPath: '/beheer'
      preLoaderRoute: typeof BeheerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistent': {
      id: '/assistent'
      path: '/assistent'
      fullPath: '/assistent'
      preLoaderRoute: typeof AssistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truckstops/$id': {
      id: '/truckstops/$id'
      path: '/$id'
      fullPath: '/truckstops/$id'
      preLoaderRoute: typeof TruckstopsIdRouteImport
      parentRoute: typeof TruckstopsRoute
    }
    '/terminals/$id': {
      id: '/terminals/$id'
      path: '/$id'
      fullPath: '/terminals/$id'
      preLoaderRoute: typeof TerminalsIdRouteImport
      parentRoute: typeof TerminalsRoute
    }
    '/ritten/$rideId': {
      id: '/ritten/$rideId'
      path: '/$rideId'
      fullPath: '/ritten/$rideId'
      preLoaderRoute: typeof RittenRideIdRouteImport
      parentRoute: typeof RittenRoute
    }
    '/profiel/$userId': {
      id: '/profiel/$userId'
      path: '/$userId'
      fullPath: '/profiel/$userId'
      preLoaderRoute: typeof ProfielUserIdRouteImport
      parentRoute: typeof ProfielRoute
    }
    '/konvooi/$id': {
      id: '/konvooi/$id'
      path: '/$id'
      fullPath: '/konvooi/$id'
      preLoaderRoute: typeof KonvooiIdRouteImport
      parentRoute: typeof KonvooiRoute
    }
    '/groepen/$id': {
      id: '/groepen/$id'
      path: '/$id'
      fullPath: '/groepen/$id'
      preLoaderRoute: typeof GroepenIdRouteImport
      parentRoute: typeof GroepenRoute
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/beheer/meldingen': {
      id: '/beheer/meldingen'
      path: '/meldingen'
      fullPath: '/beheer/meldingen'
      preLoaderRoute: typeof BeheerMeldingenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/locaties': {
      id: '/beheer/locaties'
      path: '/locaties'
      fullPath: '/beheer/locaties'
      preLoaderRoute: typeof BeheerLocatiesRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/gebruikers': {
      id: '/beheer/gebruikers'
      path: '/gebruikers'
      fullPath: '/beheer/gebruikers'
      preLoaderRoute: typeof BeheerGebruikersRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/auditlog': {
      id: '/beheer/auditlog'
      path: '/auditlog'
      fullPath: '/beheer/auditlog'
      preLoaderRoute: typeof BeheerAuditlogRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/api/public/here-key': {
      id: '/api/public/here-key'
      path: '/api/public/here-key'
      fullPath: '/api/public/here-key'
      preLoaderRoute: typeof ApiPublicHereKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BeheerRouteChildren {
  BeheerAuditlogRoute: typeof BeheerAuditlogRoute
  BeheerGebruikersRoute: typeof BeheerGebruikersRoute
  BeheerLocatiesRoute: typeof BeheerLocatiesRoute
  BeheerMeldingenRoute: typeof BeheerMeldingenRoute
}

const BeheerRouteChildren: BeheerRouteChildren = {
  BeheerAuditlogRoute: BeheerAuditlogRoute,
  BeheerGebruikersRoute: BeheerGebruikersRoute,
  BeheerLocatiesRoute: BeheerLocatiesRoute,
  BeheerMeldingenRoute: BeheerMeldingenRoute,
}

const BeheerRouteWithChildren =
  BeheerRoute._addFileChildren(BeheerRouteChildren)

interface ChatRouteChildren {
  ChatChatIdRoute: typeof ChatChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatIdRoute: ChatChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface GroepenRouteChildren {
  GroepenIdRoute: typeof GroepenIdRoute
}

const GroepenRouteChildren: GroepenRouteChildren = {
  GroepenIdRoute: GroepenIdRoute,
}

const GroepenRouteWithChildren =
  GroepenRoute._addFileChildren(GroepenRouteChildren)

interface KonvooiRouteChildren {
  KonvooiIdRoute: typeof KonvooiIdRoute
}

const KonvooiRouteChildren: KonvooiRouteChildren = {
  KonvooiIdRoute: KonvooiIdRoute,
}

const KonvooiRouteWithChildren =
  KonvooiRoute._addFileChildren(KonvooiRouteChildren)

interface ProfielRouteChildren {
  ProfielUserIdRoute: typeof ProfielUserIdRoute
}

const ProfielRouteChildren: ProfielRouteChildren = {
  ProfielUserIdRoute: ProfielUserIdRoute,
}

const ProfielRouteWithChildren =
  ProfielRoute._addFileChildren(ProfielRouteChildren)

interface RittenRouteChildren {
  RittenRideIdRoute: typeof RittenRideIdRoute
}

const RittenRouteChildren: RittenRouteChildren = {
  RittenRideIdRoute: RittenRideIdRoute,
}

const RittenRouteWithChildren =
  RittenRoute._addFileChildren(RittenRouteChildren)

interface TerminalsRouteChildren {
  TerminalsIdRoute: typeof TerminalsIdRoute
}

const TerminalsRouteChildren: TerminalsRouteChildren = {
  TerminalsIdRoute: TerminalsIdRoute,
}

const TerminalsRouteWithChildren = TerminalsRoute._addFileChildren(
  TerminalsRouteChildren,
)

interface TruckstopsRouteChildren {
  TruckstopsIdRoute: typeof TruckstopsIdRoute
}

const TruckstopsRouteChildren: TruckstopsRouteChildren = {
  TruckstopsIdRoute: TruckstopsIdRoute,
}

const TruckstopsRouteWithChildren = TruckstopsRoute._addFileChildren(
  TruckstopsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistentRoute: AssistentRoute,
  BeheerRoute: BeheerRouteWithChildren,
  BeloningenRoute: BeloningenRoute,
  BrandstofRoute: BrandstofRoute,
  CarplayRoute: CarplayRoute,
  ChatRoute: ChatRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DeelEtaRoute: DeelEtaRoute,
  DocumentenRoute: DocumentenRoute,
  FleetRoute: FleetRoute,
  GeblokkeerdRoute: GeblokkeerdRoute,
  GroepenRoute: GroepenRouteWithChildren,
  InstellingenRoute: InstellingenRoute,
  IntegratiesRoute: IntegratiesRoute,
  KaartRoute: KaartRoute,
  KonvooiRoute: KonvooiRouteWithChildren,
  LoginRoute: LoginRoute,
  MeerRoute: MeerRoute,
  MeldingenRoute: MeldingenRoute,
  NavigatieRoute: NavigatieRoute,
  NavigatieProviderRoute: NavigatieProviderRoute,
  NotificatiesRoute: NotificatiesRoute,
  OfflineKaartenRoute: OfflineKaartenRoute,
  OnboardingRoute: OnboardingRoute,
  OnderhoudRoute: OnderhoudRoute,
  OntdekkenRoute: OntdekkenRoute,
  OverRoute: OverRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacybeleidRoute: PrivacybeleidRoute,
  ProfielRoute: ProfielRouteWithChildren,
  ReleaseNotesRoute: ReleaseNotesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RittenRoute: RittenRouteWithChildren,
  RouteplannerRoute: RouteplannerRoute,
  TerminalsRoute: TerminalsRouteWithChildren,
  TruckstopsRoute: TruckstopsRouteWithChildren,
  VoertuigRoute: VoertuigRoute,
  VoorwaardenRoute: VoorwaardenRoute,
  VoorzieningenRoute: VoorzieningenRoute,
  ZoekenRoute: ZoekenRoute,
  ApiPublicHereKeyRoute: ApiPublicHereKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
