/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoorzieningenRouteImport } from './routes/voorzieningen'
import { Route as VoertuigRouteImport } from './routes/voertuig'
import { Route as TruckstopsRouteImport } from './routes/truckstops'
import { Route as RittenRouteImport } from './routes/ritten'
import { Route as ProfielRouteImport } from './routes/profiel'
import { Route as OntdekkenRouteImport } from './routes/ontdekken'
import { Route as NavigatieRouteImport } from './routes/navigatie'
import { Route as MeldingenRouteImport } from './routes/meldingen'
import { Route as KaartRouteImport } from './routes/kaart'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrandstofRouteImport } from './routes/brandstof'
import { Route as BeloningenRouteImport } from './routes/beloningen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TruckstopsIdRouteImport } from './routes/truckstops.$id'
import { Route as RittenRideIdRouteImport } from './routes/ritten.$rideId'
import { Route as ProfielUserIdRouteImport } from './routes/profiel.$userId'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'

const VoorzieningenRoute = VoorzieningenRouteImport.update({
  id: '/voorzieningen',
  path: '/voorzieningen',
  getParentRoute: () => rootRouteImport,
} as any)
const VoertuigRoute = VoertuigRouteImport.update({
  id: '/voertuig',
  path: '/voertuig',
  getParentRoute: () => rootRouteImport,
} as any)
const TruckstopsRoute = TruckstopsRouteImport.update({
  id: '/truckstops',
  path: '/truckstops',
  getParentRoute: () => rootRouteImport,
} as any)
const RittenRoute = RittenRouteImport.update({
  id: '/ritten',
  path: '/ritten',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfielRoute = ProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const OntdekkenRoute = OntdekkenRouteImport.update({
  id: '/ontdekken',
  path: '/ontdekken',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatieRoute = NavigatieRouteImport.update({
  id: '/navigatie',
  path: '/navigatie',
  getParentRoute: () => rootRouteImport,
} as any)
const MeldingenRoute = MeldingenRouteImport.update({
  id: '/meldingen',
  path: '/meldingen',
  getParentRoute: () => rootRouteImport,
} as any)
const KaartRoute = KaartRouteImport.update({
  id: '/kaart',
  path: '/kaart',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandstofRoute = BrandstofRouteImport.update({
  id: '/brandstof',
  path: '/brandstof',
  getParentRoute: () => rootRouteImport,
} as any)
const BeloningenRoute = BeloningenRouteImport.update({
  id: '/beloningen',
  path: '/beloningen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruckstopsIdRoute = TruckstopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TruckstopsRoute,
} as any)
const RittenRideIdRoute = RittenRideIdRouteImport.update({
  id: '/$rideId',
  path: '/$rideId',
  getParentRoute: () => RittenRoute,
} as any)
const ProfielUserIdRoute = ProfielUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfielRoute,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beloningen': typeof BeloningenRoute
  '/brandstof': typeof BrandstofRoute
  '/chat': typeof ChatRouteWithChildren
  '/community': typeof CommunityRoute
  '/instellingen': typeof InstellingenRoute
  '/kaart': typeof KaartRoute
  '/meldingen': typeof MeldingenRoute
  '/navigatie': typeof NavigatieRoute
  '/ontdekken': typeof OntdekkenRoute
  '/profiel': typeof ProfielRouteWithChildren
  '/ritten': typeof RittenRouteWithChildren
  '/truckstops': typeof TruckstopsRouteWithChildren
  '/voertuig': typeof VoertuigRoute
  '/voorzieningen': typeof VoorzieningenRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/profiel/$userId': typeof ProfielUserIdRoute
  '/ritten/$rideId': typeof RittenRideIdRoute
  '/truckstops/$id': typeof TruckstopsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beloningen': typeof BeloningenRoute
  '/brandstof': typeof BrandstofRoute
  '/chat': typeof ChatRouteWithChildren
  '/community': typeof CommunityRoute
  '/instellingen': typeof InstellingenRoute
  '/kaart': typeof KaartRoute
  '/meldingen': typeof MeldingenRoute
  '/navigatie': typeof NavigatieRoute
  '/ontdekken': typeof OntdekkenRoute
  '/profiel': typeof ProfielRouteWithChildren
  '/ritten': typeof RittenRouteWithChildren
  '/truckstops': typeof TruckstopsRouteWithChildren
  '/voertuig': typeof VoertuigRoute
  '/voorzieningen': typeof VoorzieningenRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/profiel/$userId': typeof ProfielUserIdRoute
  '/ritten/$rideId': typeof RittenRideIdRoute
  '/truckstops/$id': typeof TruckstopsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beloningen': typeof BeloningenRoute
  '/brandstof': typeof BrandstofRoute
  '/chat': typeof ChatRouteWithChildren
  '/community': typeof CommunityRoute
  '/instellingen': typeof InstellingenRoute
  '/kaart': typeof KaartRoute
  '/meldingen': typeof MeldingenRoute
  '/navigatie': typeof NavigatieRoute
  '/ontdekken': typeof OntdekkenRoute
  '/profiel': typeof ProfielRouteWithChildren
  '/ritten': typeof RittenRouteWithChildren
  '/truckstops': typeof TruckstopsRouteWithChildren
  '/voertuig': typeof VoertuigRoute
  '/voorzieningen': typeof VoorzieningenRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/profiel/$userId': typeof ProfielUserIdRoute
  '/ritten/$rideId': typeof RittenRideIdRoute
  '/truckstops/$id': typeof TruckstopsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beloningen'
    | '/brandstof'
    | '/chat'
    | '/community'
    | '/instellingen'
    | '/kaart'
    | '/meldingen'
    | '/navigatie'
    | '/ontdekken'
    | '/profiel'
    | '/ritten'
    | '/truckstops'
    | '/voertuig'
    | '/voorzieningen'
    | '/chat/$chatId'
    | '/profiel/$userId'
    | '/ritten/$rideId'
    | '/truckstops/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beloningen'
    | '/brandstof'
    | '/chat'
    | '/community'
    | '/instellingen'
    | '/kaart'
    | '/meldingen'
    | '/navigatie'
    | '/ontdekken'
    | '/profiel'
    | '/ritten'
    | '/truckstops'
    | '/voertuig'
    | '/voorzieningen'
    | '/chat/$chatId'
    | '/profiel/$userId'
    | '/ritten/$rideId'
    | '/truckstops/$id'
  id:
    | '__root__'
    | '/'
    | '/beloningen'
    | '/brandstof'
    | '/chat'
    | '/community'
    | '/instellingen'
    | '/kaart'
    | '/meldingen'
    | '/navigatie'
    | '/ontdekken'
    | '/profiel'
    | '/ritten'
    | '/truckstops'
    | '/voertuig'
    | '/voorzieningen'
    | '/chat/$chatId'
    | '/profiel/$userId'
    | '/ritten/$rideId'
    | '/truckstops/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeloningenRoute: typeof BeloningenRoute
  BrandstofRoute: typeof BrandstofRoute
  ChatRoute: typeof ChatRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  InstellingenRoute: typeof InstellingenRoute
  KaartRoute: typeof KaartRoute
  MeldingenRoute: typeof MeldingenRoute
  NavigatieRoute: typeof NavigatieRoute
  OntdekkenRoute: typeof OntdekkenRoute
  ProfielRoute: typeof ProfielRouteWithChildren
  RittenRoute: typeof RittenRouteWithChildren
  TruckstopsRoute: typeof TruckstopsRouteWithChildren
  VoertuigRoute: typeof VoertuigRoute
  VoorzieningenRoute: typeof VoorzieningenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voorzieningen': {
      id: '/voorzieningen'
      path: '/voorzieningen'
      fullPath: '/voorzieningen'
      preLoaderRoute: typeof VoorzieningenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voertuig': {
      id: '/voertuig'
      path: '/voertuig'
      fullPath: '/voertuig'
      preLoaderRoute: typeof VoertuigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truckstops': {
      id: '/truckstops'
      path: '/truckstops'
      fullPath: '/truckstops'
      preLoaderRoute: typeof TruckstopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritten': {
      id: '/ritten'
      path: '/ritten'
      fullPath: '/ritten'
      preLoaderRoute: typeof RittenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiel': {
      id: '/profiel'
      path: '/profiel'
      fullPath: '/profiel'
      preLoaderRoute: typeof ProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ontdekken': {
      id: '/ontdekken'
      path: '/ontdekken'
      fullPath: '/ontdekken'
      preLoaderRoute: typeof OntdekkenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigatie': {
      id: '/navigatie'
      path: '/navigatie'
      fullPath: '/navigatie'
      preLoaderRoute: typeof NavigatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meldingen': {
      id: '/meldingen'
      path: '/meldingen'
      fullPath: '/meldingen'
      preLoaderRoute: typeof MeldingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaart': {
      id: '/kaart'
      path: '/kaart'
      fullPath: '/kaart'
      preLoaderRoute: typeof KaartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brandstof': {
      id: '/brandstof'
      path: '/brandstof'
      fullPath: '/brandstof'
      preLoaderRoute: typeof BrandstofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beloningen': {
      id: '/beloningen'
      path: '/beloningen'
      fullPath: '/beloningen'
      preLoaderRoute: typeof BeloningenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truckstops/$id': {
      id: '/truckstops/$id'
      path: '/$id'
      fullPath: '/truckstops/$id'
      preLoaderRoute: typeof TruckstopsIdRouteImport
      parentRoute: typeof TruckstopsRoute
    }
    '/ritten/$rideId': {
      id: '/ritten/$rideId'
      path: '/$rideId'
      fullPath: '/ritten/$rideId'
      preLoaderRoute: typeof RittenRideIdRouteImport
      parentRoute: typeof RittenRoute
    }
    '/profiel/$userId': {
      id: '/profiel/$userId'
      path: '/$userId'
      fullPath: '/profiel/$userId'
      preLoaderRoute: typeof ProfielUserIdRouteImport
      parentRoute: typeof ProfielRoute
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatChatIdRoute: typeof ChatChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatIdRoute: ChatChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ProfielRouteChildren {
  ProfielUserIdRoute: typeof ProfielUserIdRoute
}

const ProfielRouteChildren: ProfielRouteChildren = {
  ProfielUserIdRoute: ProfielUserIdRoute,
}

const ProfielRouteWithChildren =
  ProfielRoute._addFileChildren(ProfielRouteChildren)

interface RittenRouteChildren {
  RittenRideIdRoute: typeof RittenRideIdRoute
}

const RittenRouteChildren: RittenRouteChildren = {
  RittenRideIdRoute: RittenRideIdRoute,
}

const RittenRouteWithChildren =
  RittenRoute._addFileChildren(RittenRouteChildren)

interface TruckstopsRouteChildren {
  TruckstopsIdRoute: typeof TruckstopsIdRoute
}

const TruckstopsRouteChildren: TruckstopsRouteChildren = {
  TruckstopsIdRoute: TruckstopsIdRoute,
}

const TruckstopsRouteWithChildren = TruckstopsRoute._addFileChildren(
  TruckstopsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeloningenRoute: BeloningenRoute,
  BrandstofRoute: BrandstofRoute,
  ChatRoute: ChatRouteWithChildren,
  CommunityRoute: CommunityRoute,
  InstellingenRoute: InstellingenRoute,
  KaartRoute: KaartRoute,
  MeldingenRoute: MeldingenRoute,
  NavigatieRoute: NavigatieRoute,
  OntdekkenRoute: OntdekkenRoute,
  ProfielRoute: ProfielRouteWithChildren,
  RittenRoute: RittenRouteWithChildren,
  TruckstopsRoute: TruckstopsRouteWithChildren,
  VoertuigRoute: VoertuigRoute,
  VoorzieningenRoute: VoorzieningenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
